databases:
  - name: dataprop
    databaseName: dataprop
    user: dataprop

services:
  - type: web
    name: dataprop
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dataprop
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false